version: '3'
services:
  juice-box:
    image: bkimminich/juice-shop
    ports:
      - 3000:3000

  arachni:
    image: arachni/arachni:latest
    ports:
      - 222:22
      - 7331:7331
      - 9292:9292
  nikto:
    image: frapsoft/nikto:latest

  dvwa:
    image: vulnerables/web-dvwa
    ports:
    - 1300:80

  zap-proxy:
    image: owasp/zap2docker-stable
    command: zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=5364864132243598723485
    ports:
      - "8090:8080"

  zap-proxy-bare:
    image: owasp/zap2docker-bare
    command: zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=5364864132243598723485
    ports:
      - "8090:8080"

  bwapp:
    image: raesene/bwapp:latest
    ports:
    - "1301:80"


  webgoat:
    image: webgoat/webgoat-8.0
    environment:
      - WEBWOLF_HOST=webwolf
      - WEBWOLF_PORT=9090
      - TZ=Europe/Amsterdam
    ports:
      - "8080:8080"
      - "9001:9001"
    volumes:
      - .:/home/webgoat/.webgoat
    working_dir: /home/webgoat

  webwolf:
    image: webgoat/webwolf
    ports:
      - "9090:9090"
    command: --spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat --server.address=0.0.0.0
    depends_on:
      - webgoat