version: '3'
services:
  juice-box:
    image: bkimminich/juice-shop
    ports:
      - 3000:3000
      
  arachni:
    image: arachni/arachni:latest
    ports:
      - 222:22
      - 7331:7331
      - 9292:9292