/*
 * ZAP API
 *
 * The HTTP API for controlling and accessing ZAP.
 *
 * API version: Dev Build
 * Contact: zaproxy-users@googlegroups.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelError struct {
	Message string `json:"message"`
	Code int32 `json:"code"`
}
